version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      timeout: 3s
      retries: 10
      interval: 3s

volumes:
  diploma_pg_data:
