version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      timeout: 6s
      retries: 10
      interval: 3s

  api:
    build: .
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      collect_static:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/opt/core/
      - ./todolist:/opt/todolist/
      - ./goals:/opt/goals/

  collect_static:
    build: .
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
    command: python3 manage.py collectstatic -c --no-input

  frontend:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  diploma_pg_data:
  django_static:
