# Generated by Django 4.0.1 on 2023-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
    ]
