# Generated by Django 4.0.1 on 2023-05-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='goal',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
