# Generated by Django 4.0.1 on 2023-05-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_category_goal_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
