# Generated by Django 4.0.1 on 2023-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='goal',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
