# Generated by Django 4.0.1 on 2023-05-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_goalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
