# Generated by Django 4.0.1 on 2023-05-06 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5236, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5489, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='boardparticipant',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5236, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='boardparticipant',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5489, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5236, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5489, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5236, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5489, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5236, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 14, 36, 45, 5489, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
    ]
