# Generated by Django 4.0.1 on 2023-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_board_created_board_updated_boardparticipant_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='boardparticipant',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='boardparticipant',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
    ]
