# Generated by Django 4.0.1 on 2023-05-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardparticipant',
            unique_together=set(),
        ),
    ]
