# Generated by Django 4.0.1 on 2023-05-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0014_alter_boardparticipant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardparticipant',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='goals.board', verbose_name='Доска'),
        ),
        migrations.AlterUniqueTogether(
            name='boardparticipant',
            unique_together={('board', 'user')},
        ),
    ]
